### ISSUE TITLE
Does not work in Safari; does in Chrome

### ISSUE THREAD

**Issue by robinbohnen** [mcvendrell/SlimFramework4LoginAuth#1]
Hi, 

Not sure why (tried a lot with CORS and code) but it isn't working in Safari.
It does (sometimes) work in Chrome but not always.
Do not get errors other than "Error:" as an alert with no content.
In apache error log; (103)Software caused connection abort, AH01075: Error dispatching request to : (reading input brigade)

Do you have any other clue where to look?

**Comment by mcvendrell** [comment]
Hummm, can you try this?

Change the *form* label to a simply *div* label in lines 6 and 21 on `public/login.html`
I got same problem on iOS and it solve the problem for me.
Was weird because in Windows (with Chrome) all worked fine, but on iOS (Safari) had exactly that problem.

If it works, do the same on `public/addData.html`

**Comment by robinbohnen** [comment]
Wow; that was it indeed. Works instant now. Thanks! :)

**Comment by mcvendrell** [comment]
You're welcome.

I will update the project too
